-- 090_the_decorative_page_gets_its_first_exemplar.sql
--
-- **The Decorative page has an exemplar, and it is the tool's own work.** Open
-- since 058. Three sourced images were rejected against TPL-10 — the garden
-- gate (073, re-typed by 088), the porch generation (082) and the decorative
-- image sourced 2026-09-21 — every one of them a place with depth rather than a
-- border with objects grouped inside it. D139 established that the page type was
-- never broken: it had simply never been run with a subject describing its own
-- composition.
--
-- `cand-F`, approved 2026-09-21. Teapot, two stacked bowls, a folded cloth, a
-- cream jug and a whole pear, overlapping and resting on one straight shelf
-- line; chevrons on the teapot, a dot row on one bowl, chevrons on the other,
-- scallop arcs on the jug; the pear and the cloth in plain outline; a
-- compartmented border on all four edges; a faceted open ground. **17.2% black,
-- 39.5 cross/1k, 20px open run** — the widest pencil gaps of any candidate and
-- less than half the crossings of the knitwear page that opened the day.
--
-- **This is the first reference in the library that the tool made itself.**
-- Every other one was sourced and hand-placed, which is why D91 found all four
-- `asset_id` columns NULL and had to record the one provable link by hand. This
-- row names its asset, so D91's triggers apply to it properly: it could only be
-- created because the asset is approved, and the asset cannot leave approved
-- while the reference is standing.
--
-- Copied into `exemplars/` rather than pointed at the job directory. The job
-- directory is generated output and ignored by git; `exemplars/` is the one
-- tracked area (088), and a reference that exists only on this machine is the
-- failure 088 was written to close. `asset_id` carries the provenance so the
-- copy is not an orphan.
--
-- Decorative goes to 1 and **087's all-six invariant is restored**, broken
-- deliberately by 088 four hours earlier.
--
-- ---
--
-- **Knit texture on a mitten is decoration, not shading — Sunshine's ruling,
-- 2026-09-21, and it corrects me rather than the data.** `cand-B`'s mittens
-- came back finely hatched, I read that as D47's "nothing is filled, shaded,
-- hatched or textured" and lifted it with `.unhatch.mjs`. His answer: *"the
-- hatched mittens are ok because mittens are knitted and have fabric detail in
-- real life."*
--
-- **D122 had already settled this and I applied the wrong half of it.** 047 was
-- written precisely because `hs-texture-as-pattern` read "form is described by
-- outline alone" and in doing so deleted the rug with a border, the quilt
-- pieced into blocks and the grain along a floorboard — a rule written to
-- protect colourability removing it. Decoration and shading are not the same
-- thing. **A feature the real object has is decoration and it stays**; tone
-- standing in for form is shading and it goes. Knit on a mitten, weave on a
-- basket, grain on a board are all the first kind.
--
-- The line that still holds is D122's own: decoration is drawn as **further
-- closed shapes each large enough to take a pencil**. Cable bands and visible
-- stitches qualify; so does the cuff ribbing that was left in place. That is a
-- question about how the texture is drawn, not about whether the object may
-- have any — and the second question is the one I got wrong.
--
-- Recorded here because it will otherwise be re-litigated: the next pass that
-- measures a hatched mitten will flag it again, exactly as this one did.

begin;

insert into reference_images
  (item_id, asset_id, label, storage_path, kind, page_type, art_style,
   usable_as_input, notes)
values
  (null, '2f6f71f4-ef77-45e8-b0d6-6e1fda3afee0',
   'Decorative page — fall breakfast panel',
   'exemplars/decorative-fall-breakfast-panel.png', 'exemplar',
   'Decorative page', 'Geometric Abstract', true,
   'Generated by this tool on TPL-10 and approved by Sunshine 2026-09-21 — the '
   'first reference in the library that is not sourced. A teapot, two stacked '
   'bowls, a folded cloth, a cream jug and a whole pear, overlapping and '
   'resting on one straight shelf line, with a pattern band on each vessel and '
   'the fruit left plain; compartmented border on all four edges; faceted open '
   'ground, no horizon and nothing receding. 17.2% black, 39.5 cross/1k, 20px '
   'open run. It teaches the two things TPL-10 asks for and no previous '
   'candidate showed: a border that runs all the way round, and a centre group '
   'that rests on one line instead of floating up the page (081, 082).');

do $$
declare n int;
begin
  select count(*) into n from reference_images
   where usable_as_input and page_type = 'Decorative page';
  if n <> 1 then raise exception 'expected 1 decorative ref, got %', n; end if;

  -- 087's invariant, broken on purpose by 088 and restored here.
  select count(*) into n from (
    select page_type from reference_images
     where usable_as_input and page_type is not null
     group by page_type having count(*) >= 1
  ) t;
  if n <> 6 then raise exception 'only % page types have a reference', n; end if;

  -- Environment must not have moved: 088 put the garden gate there and the
  -- selection query takes four, so a silent fifth would push one out (D130).
  select count(*) into n from reference_images
   where usable_as_input and page_type = 'Environment page';
  if n <> 4 then raise exception 'expected 4 environment refs, got %', n; end if;

  -- The promotion is what makes this row different from every other one. If the
  -- asset link is ever lost, the row becomes another hand-placed seed and D91's
  -- triggers stop protecting it.
  if not exists (
    select 1 from reference_images r
      join generated_assets a on a.id = r.asset_id
     where r.storage_path = 'exemplars/decorative-fall-breakfast-panel.png'
       and a.status = 'approved'
  ) then raise exception 'the decorative exemplar lost its approved asset'; end if;
end $$;

commit;
